---
# tasks file for bind9_servers
- name: Install bind9 package.
  ansible.builtin.apt:
    name: "bind9"
    cache_valid_time: 3600
    state: present

- name: Update the Bind Options file.
  ansible.builtin.template:
    src: named.conf.options.j2
    dest: /etc/bind/named.conf.options
    mode: "0644"
  notify: Reload bind9

- name: Update the Bind Local file.
  ansible.builtin.template:
    src: named.conf.local.j2
    dest: /etc/bind/named.conf.local
    mode: "0644"
  notify: Reload bind9

# Using an include here to limit the amount of output during playbook execution.
# Loop over each zone and only "include" the tasks when the host is the primary
# name server for that zone (doesn't have forwarder or primaries defined).
- name: Include the primary name server tasks.
  ansible.builtin.include_tasks: 'primary_zone.yml'
  loop: "{{ bind9_servers_zones }}"
  loop_control:
    label: "{{ zone.name }}"
    loop_var: zone
  when:
    - zone.forwarders is not defined
    - zone.primaries is not defined

# Reloading the service inside the above loop doesn't work and
# must be done before `nsupdate` will work.
- name: Run notified handlers before attempting dynamic updates.
  ansible.builtin.meta: flush_handlers

# Using an include here for nested loops.
- name: Include the zone_update tasks for dynamic zones.
  ansible.builtin.include_tasks: 'zone_updates.yml'
  loop: "{{ bind9_servers_zones }}"
  loop_control:
    label: "{{ zone.name }}"
    loop_var: zone
  when:
    - zone.allowed_tsig_keys is defined
    - zone.forwarders is not defined
    - zone.primaries is not defined
