---
- name: "Zone_update : Get TSIG secrets for {{ zone.name }}."
  ansible.builtin.command: # noqa: command-instead-of-module
    cmd: "sed -n 's/.*secret \"\\(.*\\)\";/\\1/p' /etc/bind/tsig.{{ zone.name }}"
  changed_when: false
  register: zone_tsig_secret
  when:
    - zone.allowed_tsig_keys is defined

- name: "Zone_update : Update dynamic zone resource records using nsupdate for {{ zone.name }}."
  become: false
  community.general.nsupdate:
    key_name: '{{ zone.name }}.key'
    key_algorithm: "{{ bind9_servers_tsig_algorithm }}"
    key_secret: "{{ zone_tsig_secret.stdout }}"
    server: "{{ ansible_all_ipv4_addresses | first }}"
    record: "{{ rr[0] }}"
    ttl: "{{ omit if rr[1] | length == 0 else rr[1] }}"
    type: "{{ rr[2] }}"
    value: "{{ rr[3] }}"
    zone: "{{ zone.name }}"
  delegate_to: localhost
  loop: "{{ vars[zone.records_var] if zone.allowed_tsig_keys is defined else [] }}"
  vars:
    rr: "{{ item.split(';') }}"
  when:
    - rr | length > 1
