---
# defaults file for bind9_servers

# The domain name portion of the primary name server(s).
bind9_servers_domain_name: "{{ bind9_servers_zones[0].name }}"

# The email address to use for all zone files.
bind9_servers_email_address: "domainreg.{{ bind9_servers_domain_name }}."

# Sets 'recursion' in options to yes (true) or no (false)
bind9_servers_recursion: true

# Algorithm used for creating TSIG keys and in the `nsupdate` calls on dynamic zones.
bind9_servers_tsig_algorithm: hmac-sha512

# Default values for zone SOA records, when not specified for the zone.
bind9_servers_zone_default_expire: '2419200' # 28 days
bind9_servers_zone_default_negative_cache_ttl: '60' # 1 minute
bind9_servers_zone_default_refresh: '10800' # 3 hours
bind9_servers_zone_default_retry: '3600' # 1 hour

# The default TTL for all zone files. Set above the SOA record.
bind9_servers_zone_default_ttl: '86400' # 86400 = 24 hours

# This is the FQDN for the MName in the SOA record.
bind9_servers_zone_mname: "{{ ansible_hostname }}.{{ bind9_servers_domain_name }}."

# Provide a list of the zones for the name servers.
# The name of the first zone in this list will be the default `bind9_servers_domain_name`.
bind9_servers_zones: []
